[package]
name = "rust-ed"
version = "0.1.0"
authors = ["Learn Java <learnjavadiscord@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.13.0"
clipboard = "0.5.0"
num = "0.2.0"
